/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "var(--color-background)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-tint": "var(--color-surface-tint)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "inverse-surface": "var(--color-inverse-surface)",
        "error-container": "var(--color-error-container)",
        "surface-bright": "var(--color-surface-bright)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-background": "var(--color-on-background)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "primary": "var(--color-primary)",
        "surface": "var(--color-surface)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "tertiary": "var(--color-tertiary)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-error": "var(--color-on-error)",
        "outline": "var(--color-outline)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-secondary": "var(--color-on-secondary)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-dim": "var(--color-surface-dim)",
        "primary-container": "var(--color-primary-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "inverse-primary": "var(--color-inverse-primary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "error": "var(--color-error)",
        "on-primary-container": "var(--color-on-primary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-primary": "var(--color-on-primary)",
        "secondary": "var(--color-secondary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-surface": "var(--color-on-surface)",
        "on-error-container": "var(--color-on-error-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        // Process Colors
        "process-p1": "#3B82F6",
        "process-p2": "#22C55E",
        "process-p3": "#F59E0B",
        "process-p4": "#EC4899",
        "process-p5": "#8B5CF6"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "max-width": "1440px",
        "xl": "40px",
        "gutter": "24px",
        "md": "24px",
        "sm": "12px",
        "lg": "48px",
        "unit": "4px"
      },
      fontFamily: {
        "code-sm": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"]
      },
    },
  },
  plugins: [],
}
